name: build

on:
  push:
    branches:
      - main
      - release-test

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Extract Version
        id: extract_version
        run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Check Existing Release
        id: check_release
        run: |
          STATUSCODE=$(curl -s -o /dev/null -I -w "%{http_code}" https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.extract_version.outputs.version }})
          
          if test $STATUSCODE -n 200; then
            echo "Release with version v${{ steps.extract_version.outputs.version }} already exists. Exiting..."
            exit 1
          fi

      - name: Build Jar
        run: mvn clean package

      - name: Upload Jar
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version.outputs.version }}
          files: target/*.jar

